### ISSUE TITLE
extract-text-webpack-plugin should not be used with webpack 4

### ISSUE THREAD

**Issue by rowild** [tailwindcss/webpack-starter#29]
The `extract-text-webpack-plugin` readme clearly states, that it should not be used with `webpack 4`. Instead, `mini-css-extract-plugin` should be used.

This example should be updated accordingly.

**Comment by adamwathan** [comment]
`mini-css-extract-plugin` doesn't work the same way and doesn't allow you to extract multiple CSS files without creating a bunch of empty JS files (wasted multiple days on this recently.) Until Webpack 5 is released with support for CSS entry points this is still better.

**Comment by rowild** [comment]
@adamwathan Thanks for the quick response! I was trying to hack a PR, but without success so far. So thanks for the info!
What about `extract-css-chunks-webpack-plugin`? The "extract multiple CSS files" brought me to that idea...
However, I am sorry to say, but the given example does not work. Are you sure that any and all info is given? (I am new to tailwind and postcss, and just a basic webpack user...)

**Comment by adamwathan** [comment]
Honestly I am probably going to kill this repo before we release 1.0 and put together a different starter — I hacked this together quickly before I knew anything about Webpack at all and in general it doesn't make a ton of sense for anyone to use this for any real projects (you'll end up completely rewriting the Webpack config once you want Babel, React, Vue, whatever).

The only real purpose of this repo is to have something to clone where you can run `npm run watch` and quickly play around with Tailwind and see if you like it, so it doesn't really matter if it's using the latest and greatest ways of doing things. Good chance I switch to Parcel for the 1.0 playground repo because there's no config file to worry about at all.

**Comment by rowild** [comment]
@adamwathan Thanks for your feedback - very interesting! Always good and enriching to read/learn about how other people think about coding!
But of course - now I am disillusioned, since I am trying to setup tailwind with webpack 4 since more than 2 days already... still didn't find the "golden key"...
Looking forward to v1!
